# Delete these routes and define your own shop routes here
tsetsee_qpay_plugin_callback:
    path: /payment/capture/qpay/{payum_token}
    defaults:
        _controller: Tsetsee\SyliusQpayPlugin\Controller\QPayQRController::callbackAction
